llm_model: "google/flan-t5-base"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
data_dir: "data"
db_dir: "db"
default_pdf_name: "RAG_Paper.pdf"
#postgres_url: "postgresql://raguser:ragpass@postgres:5432/ragdb"
