name: CI - Tests & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest fastapi

    - name: Run unit tests
      run: pytest -m "unit"

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: raguser
          POSTGRES_PASSWORD: ragpass
          POSTGRES_DB: ragdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U raguser -d ragdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest fastapi psycopg2-binary

    - name: Wait for Postgres
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -U raguser -d ragdb && break
          sleep 5
        done

    - name: Run integration tests
      run: pytest -m "integration"
