name: CI - Tests & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: raguser
          POSTGRES_PASSWORD: ragpass
          POSTGRES_DB: ragdb
        options: >-
          --health-cmd="pg_isready -U raguser -d ragdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest fastapi psycopg2-binary

      # Run unit tests only (fast, no DB)
      - name: Run unit tests
        run: pytest -m "not integration"

      # Run integration tests (requires Postgres + vectorstore, etc.)
      - name: Run integration tests
        env:
          DATABASE_URL: postgresql://raguser:ragpass@localhost:5432/ragdb
        run: pytest -m "integration" -vv
